### ISSUE TITLE
Put all upstream-related fields into a section

### ISSUE THREAD

**Issue by velovix** [velovix/debutizer#59]
Before:

```yaml
upstream_repo: http://ppa.launchpad.net/velovix/debutizer/ubuntu
upstream_components: [main]
upstream_is_trusted: true
```

After:

```yaml
upstream:
  url: http://ppa.launchpad.net/velovix/debutizer/ubuntu
  components: [main]
  trusted: true
```
